# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.setWindowModality(QtCore.Qt.NonModal)
        SettingsDialog.resize(696, 440)
        SettingsDialog.setModal(True)
        self.controlBox = QtWidgets.QDialogButtonBox(SettingsDialog)
        self.controlBox.setGeometry(QtCore.QRect(330, 400, 341, 32))
        self.controlBox.setOrientation(QtCore.Qt.Horizontal)
        self.controlBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.controlBox.setObjectName("controlBox")
        self.settingsList = QtWidgets.QListWidget(SettingsDialog)
        self.settingsList.setGeometry(QtCore.QRect(20, 20, 141, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.settingsList.setFont(font)
        self.settingsList.setObjectName("settingsList")
        self.stackedWidget = QtWidgets.QStackedWidget(SettingsDialog)
        self.stackedWidget.setGeometry(QtCore.QRect(180, 0, 471, 351))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 30, 461, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.performerModeCheckBox = QtWidgets.QCheckBox(self.groupBox_4)
        self.performerModeCheckBox.setGeometry(QtCore.QRect(30, 20, 299, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.performerModeCheckBox.setFont(font)
        self.performerModeCheckBox.setChecked(True)
        self.performerModeCheckBox.setObjectName("performerModeCheckBox")
        self.secondsToWaitTextBox = QtWidgets.QLineEdit(self.groupBox_4)
        self.secondsToWaitTextBox.setGeometry(QtCore.QRect(250, 50, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.secondsToWaitTextBox.setFont(font)
        self.secondsToWaitTextBox.setObjectName("secondsToWaitTextBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(30, 50, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 20, 451, 71))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.hostAddressTextBox = QtWidgets.QLineEdit(self.groupBox)
        self.hostAddressTextBox.setGeometry(QtCore.QRect(90, 30, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hostAddressTextBox.setFont(font)
        self.hostAddressTextBox.setObjectName("hostAddressTextBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(210, 30, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.hostPortTextBox = QtWidgets.QLineEdit(self.groupBox)
        self.hostPortTextBox.setGeometry(QtCore.QRect(250, 30, 41, 20))
        self.hostPortTextBox.setText("")
        self.hostPortTextBox.setObjectName("hostPortTextBox")
        self.autoDetectButton = QtWidgets.QPushButton(self.groupBox)
        self.autoDetectButton.setGeometry(QtCore.QRect(320, 30, 101, 23))
        self.autoDetectButton.setObjectName("autoDetectButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 130, 451, 131))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.serverOnStartupCheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.serverOnStartupCheckBox.setGeometry(QtCore.QRect(20, 30, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.serverOnStartupCheckBox.setFont(font)
        self.serverOnStartupCheckBox.setObjectName("serverOnStartupCheckBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.maxConnectedClientsTextBox = QtWidgets.QLineEdit(self.groupBox_2)
        self.maxConnectedClientsTextBox.setGeometry(QtCore.QRect(280, 70, 71, 20))
        self.maxConnectedClientsTextBox.setObjectName("maxConnectedClientsTextBox")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_3)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 20, 451, 341))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 50, 331, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchFolderList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.searchFolderList.setFont(font)
        self.searchFolderList.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.searchFolderList.setObjectName("searchFolderList")
        self.verticalLayout.addWidget(self.searchFolderList)
        self.updDatabaseButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.updDatabaseButton.setObjectName("updDatabaseButton")
        self.verticalLayout.addWidget(self.updDatabaseButton)
        self.browseButton = QtWidgets.QPushButton(self.groupBox_3)
        self.browseButton.setGeometry(QtCore.QRect(360, 50, 81, 23))
        self.browseButton.setObjectName("browseButton")
        self.removeButton = QtWidgets.QPushButton(self.groupBox_3)
        self.removeButton.setGeometry(QtCore.QRect(360, 80, 81, 23))
        self.removeButton.setObjectName("removeButton")
        self.stackedWidget.addWidget(self.page_3)

        self.retranslateUi(SettingsDialog)
        self.stackedWidget.setCurrentIndex(1)
        self.controlBox.accepted.connect(SettingsDialog.accept)
        self.controlBox.rejected.connect(SettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Dialog"))
        self.groupBox_4.setTitle(_translate("SettingsDialog", "General settings"))
        self.performerModeCheckBox.setText(_translate("SettingsDialog", "Performer Mode"))
        self.label_5.setText(_translate("SettingsDialog", "Set seconds to wait  between songs"))
        self.groupBox.setTitle(_translate("SettingsDialog", "Network settings"))
        self.label_2.setText(_translate("SettingsDialog", "IP Address"))
        self.hostAddressTextBox.setInputMask(_translate("SettingsDialog", "000.000.000.000"))
        self.label_3.setText(_translate("SettingsDialog", "Port"))
        self.hostPortTextBox.setInputMask(_translate("SettingsDialog", "00000"))
        self.autoDetectButton.setText(_translate("SettingsDialog", "Auto detect"))
        self.groupBox_2.setTitle(_translate("SettingsDialog", "Karaoke server settings"))
        self.serverOnStartupCheckBox.setText(_translate("SettingsDialog", "Automatically start the server"))
        self.label_4.setText(_translate("SettingsDialog", "Set Max Number of Clients (-1 = Unlimited)"))
        self.groupBox_3.setTitle(_translate("SettingsDialog", "Add songs to the database"))
        self.updDatabaseButton.setText(_translate("SettingsDialog", "Update Database"))
        self.browseButton.setText(_translate("SettingsDialog", "Browse..."))
        self.removeButton.setText(_translate("SettingsDialog", "Remove"))

